#!/usr/bin/env bash
# Redirect /redirect_me to another page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sed -i '$a\
server {\
    listen 80;\
    listen [::]:80;\
\
    root   /etc/nginx/html;\
    index  index.html;\
    location /redirect_me {\
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }\
}' /etc/nginx/sites-available/default

service nginx restart

