#!/usr/bin/env bash
# Redirect /redirect_me to another page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
echo 'Hello World!' > /var/www/html/index.html
printf "server {
    listen 80;
    listen [::]:80;

    root   /var/www/html;
    index  index.html;
    location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

service nginx restart

