#!/usr/bin/env bash
# Redirect /redirect_me to another page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/r /dev/stdin' /etc/nginx/sites-available/default <<EOF

    	location /redirect_me {
            	 return 301 https://google.com;
	}

    	error_page 404 /404.html;
    	location = /404.html {
		 root /var/www/html;
		 internal;
    	}     
EOF

service nginx restart

