#!/usr/bin/env bash
#install and configure HAproxy

apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
yes | add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*

echo "ENABLED=1" > /etc/default/haproxy

cat <<EOF >> /etc/haproxy/haproxy.cfg

frontend http
	 bind *:80
	 mode http
    	 default_backend web-backend

backend web-backend
	balance roundrobin
	server 271647-web-01 18.234.107.108:80 check
	server 271647-web-02 18.207.235.223:80 check

EOF

service haproxy start
