#!/usr/bin/env bash
#install and configure HAproxy

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service start nginx

apt-get -y install --no-install-recommends software-properties-common
yes | add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*

cat <<EOF >> /etc/haproxy/haproxy.cfg
frontend http
	 bind *:80
	 mode http
    	 default_backend web-backend

backend web-backend
	balance roundrobin
		server 271647-web-01 18.234.107.108:80 check
		server 271647-web-02 54.174.243.149:80 check

EOF

service restart haproxy
