#!/usr/bin/env bash
#Run nginx as nginx user


chown -R nginx:nginx /etc/nginx
chown -R nginx:nginx /var/lib/nginx

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/listen 80;/listen 8080;/g" /etc/nginx/sites-available/default

sudo -u nginx service nginx restart
