#!/usr/bin/env bash
#Run nginx as nginx user

# Create the nginx user if it doesn't exist
id -u nginx &>/dev/null || useradd -r nginx

chown -R nginx:nginx /etc/nginx
chown -R nginx:nginx /var/lib/nginx

sed -i "s/user root;/user nginx;/g; s/listen 80;/listen 8080;/g" /etc/nginx/sites-available/default

sudo -u nginx service nginx start
